apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- imapfilter.yaml

configMapGenerator:
  - name: imapfilter-cm
    literals:
    - git-clone-args="--branch main"

secretGenerator:
  - name: git-creds
    literals:
    - ssh-privatekey=your clear ssh private key
  - name: email-creds
    literals:
    - creds.lua=imapfilter lua account definition file  