apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: imapfiter
commonLabels:
  app.kubernetes.io/part-of: imapfilter

resources:
- imapfilter.yaml

configMapGenerator:
  - name: imapfilter-cm
    literals:
    - git-clone-args="--branch main"

secretGenerator:
  - name: git-creds
  - name: email-creds
    literals:
    - creds.lua=imapfilter lua account definition file  